const mongoose = require("mongoose");

const playerSchema = new mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    high_school: String,
    age: Number,
    team: String,
    birth_state: {type: String, default: null},
    height: String,
    last_name: String,
    metadata: {type: String, default: null},
    pandascore_id: {type: String, default: null},
    sport: String,
    practice_description: {type: String, default: null},
    search_rank: Number,
    years_exp: Number,
    search_first_name: String,
    weight: String,
    news_updated: {type: String, default: null},
    player_id: String,
    full_name: String,
    birth_city: {type: String, default: null},
    status: String,
    stats_id: Number,
    rotowire_id: Number,
    fantasy_data_id: Number,
    search_last_name: String,
    injury_body_part: {type: String, default: null},
    rotoworld_id: Number,
    position: String,
    sportradar_id: String,
    practice_participation: {type: String, default: null},
    injury_notes: {type: String, default: null},
    espn_id: Number,
    birth_country: {type: String, default: null},
    yahoo_id: Number,
    number: Number,
    gsis_id: {type: String, default: null},
    injury_status: {type: String, default: null},
    search_full_name: String,
    hashtag: String,
    injury_start_date: {type: String, default: null},
    college: String,
    birth_date: String, 
    active: Boolean,
    fantasy_positions: mongoose.Schema.Types.Mixed,
    first_name: String,
    swish_id: {type: String, default: null},
    depth_chart_order: {type: String, default: null},
    depth_chart_position: {type: String, default: null},
})

module.exports = mongoose.model("Player", playerSchema);